apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-private
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:lm-academy/argocd-course-private-repo-demo.git
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
